# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 1.3
  - nightly
notifications:
  email: false
git:
  depth: 999999
coveralls: true
before_script:
 - julia -e 'import Pkg; Pkg.add(Pkg.PackageSpec(url="https://github.com/jakubwro/sinewave_jll"));'
after_success:
 - julia -e 'import Pkg; cd(Pkg.dir("SineWaves")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder());)'
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=doc/ -e 'using Pkg;Pkg.add("Documenter"); Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=doc/ doc/make.jl
      after_success: skip