name = "SineWaves"
uuid = "7e3735a1-a2b3-41bf-a145-f9557d54d374"
authors = ["Jakub Wronowski <jakubwro@users.noreply.github.com>"]
version = "0.1.0"

[deps]
sinewave_jll = "9026e745-461c-5eb7-b50a-ddb23c07924d"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[targets]
test = ["Test", "FFTW"]
